# Generated by Django 3.1.4 on 2020-12-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201217_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
