# Generated by Django 3.1.4 on 2020-12-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
