# Generated by Django 3.1.4 on 2021-01-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20201217_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
